.PHONY: clean All

All:
	@echo "----------Building project:[ first-assignment - Debug ]----------"
	@cd "first-assignment" && "$(MAKE)" -f  "first-assignment.mk"
clean:
	@echo "----------Cleaning project:[ first-assignment - Debug ]----------"
	@cd "first-assignment" && "$(MAKE)" -f  "first-assignment.mk" clean
